# Generated by Django 3.2 on 2023-05-24 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timing_model',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='timing_model',
            name='ending_date',
        ),
        migrations.RemoveField(
            model_name='timing_model',
            name='starting_date',
        ),
        migrations.AlterField(
            model_name='timing_model',
            name='ending_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='timing_model',
            name='starting_time',
            field=models.DateTimeField(),
        ),
    ]
